### ISSUE TITLE
是否要为整个社区开启SSL支持

### ISSUE THREAD

**Issue by seisman** [gmt-china/developments#2]
若启用SSL，所以网站将从http改成https，因而网站中很多链接都需要修改，因而需要尽早决定。

具体费用尚不确定，但应该很便宜或者免费。

**Comment by wangliang1989** [comment]
必要程度来说，只有用户密码、密保和注册邮箱需要保密，其他本来就是公开的

**Comment by wangliang1989** [comment]
我为什么有close issue的权限？

**Comment by seisman** [comment]
开始SSL的目的有两个，一个是用户信息的加密，主要是论坛部分；另一个是防止运营商劫持，主要体现在给一个没有广告的网站强行加上自己的网站。

PS：你现在是组织成员，所以有大部分权限。

**Comment by wangliang1989** [comment]
有加密肯定有好处。我担心的是网速和GFW

**Comment by wangliang1989** [comment]
如果没有这两个问题，我支持加密

**Comment by seisman** [comment]
暂时不开启。
