### ISSUE TITLE
如何引导用户参与到文档维护中

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/developments#4]
我和一些人接触后，感受是多数人不理解我们对用户参与到文档维护中的期盼。有些人给我说发现过错误，我问哪里有错，对方说以后看到再说吧。
在这样的实际的面前，可能只有很少部分人愿意学习git，到github上参与维护。
我的建议是
1.用户中建立编辑这样的群体。
2.网页文档上提供一个报错按钮，用户发现错误后即可点击，无须登陆就可给编辑留言进行处理
3.可以有专门的版块让用户可以通过发帖的形式提交大段的翻译和讲解，经编辑进行处理
4.应该指定用户有贡献后应该给予不同程度的非物质奖励的制度

**Comment by seisman** [comment]
出现这样的状况，我也能够理解，毕竟反馈本身就是一件步骤繁琐的事情。

对于PDF文档而言，反馈的唯一方式就是将所有错误一一记下来，然后发邮件给维护者。

对于网页版来说，要稍微好一些。不过，除非本身就是github用户，或者是有很强的维护意愿，否则直接在github上参与维护的可能性几乎为零。

关于你的建议：
1. 可以建立QQ群，群成员是社区的核心维护者
2. 目前的做法是在文档中的每一个页面的底部加上评论功能。支持匿名评论，也可以通过QQ、微信等账户登陆。这是能实现的最简单的反馈方式。另外大部分页面都加上了“Edit on GitHub”的按钮，github用户也可以比较方便地直接维护
3. 在问答社区的社区发展版块里可以考虑
4. 可以在问答社区里人为增加积分，但积分功能是否要启用还不确定
