### ISSUE TITLE
为所有项目加上LICENSE

### ISSUE THREAD

**Issue by seisman** [gmt-china/developments#5]
- GMT_docs：CC BY-NC 4.0
- GMT_examples：CC BY-NC 4.0
- GMT_modules：CC BY-NC 4.0
- gmt-easy-installer: CC0 v1.0 Universal

**Comment by wangliang1989** [comment]
cc

**Comment by seisman** [comment]
官方回复：http://gmt.soest.hawaii.edu/boards/1/topics/3419

**Comment by seisman** [comment]
Fixed
