### ISSUE TITLE
2016年后社区的发展记录？

### ISSUE THREAD

**Issue by core-man** [gmt-china/developments#7]

**Comment by wangliang1989** [comment]
社区最开始是seisman写的gmt5手册，当时在seisman博客下面。QQ群就是那个gmt学习群。群名称该过，最初的名字我也忘了。你想写一个历史？2016年下半年以后基本就是现在这样，其实去前年社区没有什么进展，我记忆里是这样。你可以去看那个博文数量。去前年的博文和commit应该都比较少。

**Comment by core-man** [comment]
**社区发展时间线**的信息需要更新，例如  gmt-china.github.io 已经不存在了。http://modules.gmt-china.org 和 http://examples.gmt-china.org 也都不存在了。

**Comment by wangliang1989** [comment]
好像没有社区发展时间线，你想做什么？

**Comment by core-man** [comment]
整理中文社区的发展历史和维护信息
